[config]
reload_apps = true

[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.kitty]

input_path = '/home/abatu/.config/matugen/templates/kitty-colors.css'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.gtk3]
input_path = '/home/abatu/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark && flatpak override --user --filesystem=xdg-config/gtk-3.0'

[templates.gtk4]
input_path = '/home/abatu/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'flatpak override --user --filesystem=xdg-config/gtk-4.0'

[templates.qt5ct]
input_path = '/home/abatu/.config/matugen/templates/qt.css'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '/home/abatu/.config/matugen/templates/qt.css'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.pywalfox]
input_path = '/home/abatu/.config/matugen/templates/pywall-fox.css'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.yazi]
input_path = '/home/abatu/.config/matugen/templates/yazi.css'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = '/home/abatu/.config/matugen/templates/btop.css'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.neovim]
input_path = '~/.config/matugen/templates/template.lua'
output_path = '~/.config/nvim/generated.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.waybar]
input_path = '/home/abatu/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.vicinae]
input_path = '/home/abatu/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.hyprland]
input_path = '/home/abatu/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.starship]
input_path = '/home/abatu/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.spicetify]
input_path = '/home/abatu/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/matugen/color.ini'
post_hook = '/home/abatu/.config/matugen/scripts/spicetify_theme.sh'

[templates.Obsidian]
input_path = '/home/abatu/.config/matugen/templates/obsidian.css'
output_path = '/home/abatu/Documents/Obsidian Vault/.obsidian/snippets/mytheme.css'

[templates.Ayugram]
input_path = '/home/abatu/.config/matugen/templates/Ayugram.tdesktop-theme'
output_path = '/home/abatu/Mein-scripts/colors.tdesktop-palette'

[templates.userChrome]
input_path = '/home/abatu/.config/matugen/templates/userChrome.css.tpl'
output_path = '/home/abatu/.zen/h19bdl74.Default (release)/chrome/userChrome.css'

[templates.userContent]
input_path = '/home/abatu/.config/matugen/templates/userContent.css.tpl'
output_path = '/home/abatu/.zen/h19bdl74.Default (release)/chrome/userContent.css'
post_hook = 'echo $HOME/.mozilla/Zen/*.default-release/chrome'
