# : Manager [[[

[mgr]
cwd = { fg = "#dfe4dd" }

# Tab
tab_active = { fg = "#003822", bg = "#91d5ad", bold = true }
tab_inactive = { fg = "#acf2c8", bg = "#002112" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#62c9f0", bg = "#62c9f0" }
marker_cut = { fg = "#bfe9f9", bg = "#bfe9f9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a4cddc", bg = "#a4cddc" }

# Count
count_copied = { fg = "#001f28", bg = "#bfe9f9" }
count_cut = { fg = "#001f28", bg = "#bfe9f9" }
count_selected = { fg = "#003822", bg = "#a4cddc" }

# Border
border_symbol = " "
border_style  = { fg = "#91d5ad" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003822", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#91d5ad", fg = "#003822", bold = true }
normal_alt  = { bg = "#404943", fg = "#c0c9c0" }

# Select mode
select_main = { bg = "#b5ccbb", fg = "#203529", bold = true }
select_alt  = { bg = "#404943", fg = "#c0c9c0" }

# Unset mode
unset_main = { bg = "#a4cddc", fg = "#043542", bold = true }
unset_alt  = { bg = "#404943", fg = "#c0c9c0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#91d5ad", bg = "#353b36" }
progress_error = { fg = "#ffb4ab", bg = "#353b36" }

# Permissions
permissions_t = { fg = "#5f896a" }
permissions_w = { fg = "#408ba7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#33b9ec" }
permissions_s = { fg = "#28dd70" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#91d5ad" }
active = { fg = "#a4cddc", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#91d5ad" }
value = { fg = "#dfe4dd" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#91d5ad", bold = true, bg = "#0f1511" }
inactive = { fg = "#b5ccbb", bg = "#0f1511" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#91d5ad", bg = "#003822" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#91d5ad" }
title = {}
hovered = { fg = "#bfe9f9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353b36" }
cand = { fg = "#91d5ad" }
rest = { fg = "#003822" }
desc = { fg = "#dfe4dd" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dfe4dd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe4dd" }
run = { fg = "#dfe4dd" }
footer = { fg = "#203529", bg = "#b5ccbb" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a4cddc" }
title_warn = { fg = "#91d5ad" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dfe4dd" },
    { name = "*/", fg = "#91d5ad" },
]

# : ]]]
